services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    depends_on:
      - account_db
    env_file: ./account/.env
    restart: on-failure
    ports:
      - "8080:8080"
  
  catalog:
    build:
      context: .
      dockerfile: ./catalog/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      DATABASE_URL: http://catalog_db:9200
    restart: on-failure

  account_db:
    build:
      context: ./account
      dockerfile: ./db.dockerfile
    env_file: ./account/.env
    restart: unless-stopped
    
  catalog_db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    env_file: .env
 